server:
  port: 0
  # S3 연동
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  cloud:
    aws:
      credentials:
        accessKey: ${AWS_ACCESS_KEY}
        secretKey: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: playdata-team3

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/orderservice?serverTimezone=Asia/Seoul
    username: spring
    password: spring
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
  config:


jwt:
  expiration: 1
  secretKey: rI9KLc/nWq+0ehvbQXjST52lIHi+A4PurdKwAe0ZcN+0LE1QBv7p0qhFx8wzt8PaigtMXpJHdIl6p4ILsLDasA==

  secretKeyRt: rI9KLc/nWq+0ehvbQXjST52lIHi+A4PurdKwAe0ZcN+0LE1QBv7p0qhFx8wzt8PaigtMXpJHdIl6p4ILsLDasA==
  expirationRt: 2
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    instance:
      instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
